apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lims-frontend
  namespace: argocd
spec:
  project: lims
  source:
    repoURL: https://github.com/efangly/thanes-gitops.git
    targetRevision: main
    path: frontend/
  destination:
    server: https://kubernetes.default.svc
    namespace: thanes-lims
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: false
