apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lims
  namespace: argocd
spec:
  description: thanes-lims (frontend + backend)
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
